config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'home#index'

  resources :artists
  resources :modalities
  resources :institutions

  namespace :api do
    scope :v1 do
      mount_devise_token_auth_for "User", at: 'auth'
    end
  end

  namespace :api, defaults: { format: :json } do
    scope module: :v1, path: :v1 do
      resources :artists, only: [:create, :index]
    end
  end
end

app/models/artist.rb
class Artist < ActiveRecord::Base
  belongs_to :institution
  belongs_to :modality
end

app/models/artist_registration.rb
class ArtistRegistration
  include ActiveModel::Model

  attr_accessor :name,
  :address,
  :phone,
  :email,
  :group,
  :has_production,
  :production_description,
  :other_information,
  :note,
  :modality_name,
  :institution_name,
  :institution_address
end

app/models/institution.rb
class Institution < ActiveRecord::Base
  has_many :artist
end

app/models/modality.rb
class Modality < ActiveRecord::Base
  has_many :artist
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/api/v1/artists_controller.rb
class Api::V1::ArtistsController < ApplicationController

  def index
    render json: Artist.all, status: 200
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController

  before_action :authenticate_user!

  def index
    @artists = Artist.order(:name)
  end

  def new
    @artist = Artist.new
    @modalities = Modality.all
    @institutions = Institution.all
  end

  def show
    @artist = Artist.find(params[:id])
  end

  def edit
    @artist = Artist.find(params[:id])
    @modalities = Modality.all
    @institutions = Institution.all
  end

  def create
    @artist = Artist.new(artist_params)
    if @artist.save
      redirect_to artists_path, notice: 'Artista salvo com sucesso!'
    else
      render action: :new
    end
  end

  def update
    @artist = Artist.find(params[:id])
    if @artist.update(artist_params)
      redirect_to artists_path, notice: 'Artista atualizado com sucesso!'
    else
      render action: :edit
    end
  end

  def destroy
    @artist = Artist.find(params[:id])
    if @artist.delete
      redirect_to artists_path, notice: 'Artista removido com sucesso!'
    else
      redirect_to artists_path, alert: 'Erro ao remover artista!'
    end
  end

  private

  def artist_params
    params.require(:artist).permit(
    :name,
    :address,
    :phone,
    :email,
    :group,
    :has_production,
    :modality_id,
    :institution_id,
    :production_description,
    :other_information,
    :note
    )
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  before_action :authenticate_user!

  def index
  end

end

app/controllers/institutions_controller.rb
class InstitutionsController < ApplicationController

  before_action :authenticate_user!

  def index
    @institutions = Institution.all
  end

  def new
    @institution = Institution.new
  end

  def show
    @institution = Institution.find(params[:id])
  end

  def edit
    @institution = Institution.find(params[:id])
  end

  def create
    @institution = Institution.new(institution_params)
    if @institution.save
      redirect_to institutions_path, notice: 'Instituição cadastrada com sucesso!'
    else
      render action: :new
    end
  end

  def update
    @institution = Institution.find(params[:id])
    if @institution.update(institution_params)
      redirect_to institutions_path, notice: 'Instituição atualizada com sucesso!'
    else
      render action: :edit
    end
  end

  def destroy
    @institution = Institution.find(params[:id])
    if @institution.delete
      redirect_to institutions_path, notice: 'Instituição removida com sucesso!'
    else
      redirect_to institutions_path, alert: 'Erro ao remover instituição!'
    end
  end

  private

  def institution_params
    params.require(:institution).permit(:name, :address)
  end
end

app/controllers/modalities_controller.rb
class ModalitiesController < ApplicationController

  before_action :authenticate_user!

  def index
    @modalities = Modality.all
  end

  def new
    @modality = Modality.new
  end

  def show
    @modality = Modality.find(params[:id])
  end

  def edit
    @modality = Modality.find(params[:id])
  end

  def create
    @modality = Modality.new(modality_params)
    if @modality.save
      redirect_to modalities_path, notice: 'Modalidade artística salva com sucesso!'
    else
      render action: :new
    end
  end

  def update
    @modality = Modality.find(params[:id])
    if @modality.update(modality_params)
      redirect_to modalities_path, notice: 'Modalidade artística atualizada com sucesso!'
    else
      render action: :edit
    end
  end

  def destroy
    @modality = Modality.find(params[:id])
    if @modality.delete
      redirect_to modalities_path, notice: 'Modalidade removida com sucesso!'
    else
      redirect_to modalities_path, alert: 'Erro ao remover modalidade!'
    end
  end

  private

  def modality_params
    params.require(:modality).permit(:name)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def is_active?(controller_name)
    'active' if params[:controller] == controller_name
  end
end

app/views/artists/_form.html.erb
<%= form_for @artist do |f| %>
  <div class="row">
    <div class="form-group col-md-4">
      <%= f.label :name, 'Nome' %>
      <%= f.text_field :name, class: 'form-control'%>
    </div>
  </div>
  <div class="row">
    <div class="form-group col-md-6">
      <%= f.label :address, 'Endereço' %>
      <%= f.text_field :address, class: 'form-control'%>
    </div>
  </div>
  <div class="row">
    <div class="form-group col-md-3">
      <%= f.label :phone, 'Telefone' %>
      <%= f.text_field :phone, class: 'form-control'%>
    </div>
  </div>
  <div class="row">
    <div class="form-group col-md-3">
      <%= f.label :email, 'E-mail' %>
      <%= f.email_field :email, class: 'form-control'%>
    </div>
  </div>
  <div class="row">
    <div class="form-group col-md-4">
      <%= f.label :group, 'Grupo de arte' %>
      <%= f.text_field :group, class: 'form-control'%>
    </div>
  </div>
  <div class="row">
    <div class="form-group col-md-4">
      <%= f.label :modality, 'Modalidade artística' %>
      <%= select("artist", "modality_id", @modalities.collect { |m| [m.name, m.id] }, {include_blank: true}, class: 'form-control') %>
    </div>
  </div>
  <div class="row">
    <div class="form-group col-md-4">
      <%= f.label :institution, 'Instituição' %>
      <%= select("artist", "institution_id", @institutions.collect { |i| [i.name, i.id] }, {include_blank: true}, class: 'form-control') %>
    </div>
  </div>
  <div class="row">
    <div class="form-group col-md-4">
      <div class="row">
        <div class="col-md-12">
          <label>Já tem alguma produção realizada?</label>
          <br />
          <%= f.radio_button :has_production, 'true', :value => true %>
          <%= f.label :has_production, 'Sim' %>
          <br />
          <%= f.radio_button :has_production, 'false', :value => false %>
          <%= f.label :has_production, 'Não' %>
        </div>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="form-group col-md-6">
      <%= f.label :production_description, 'Descreva as produções realizadas, caso existam' %>
      <%= f.text_area :production_description, class: 'form-control', rows: 3 %>
    </div>
  </div>
  <div class="row">
    <div class="form-group col-md-6">
      <%= f.label :other_information, 'Outras informações' %>
      <%= f.text_area :other_information, class: 'form-control', rows: 3 %>
    </div>
  </div>
  <div class="row">
    <div class="form-group col-md-6">
      <%= f.label :note, 'Observações' %>
      <%= f.text_area :note, class: 'form-control', rows: 3 %>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12">
      <%= f.submit 'Salvar', class: 'btn btn-primary btn-lg' %>
    </div>
  </div>
<% end %>

app/views/artists/index.html.erb
<div class="row">
  <div class="col-md-12">
    <%= link_to raw("<span class='glyphicon glyphicon-plus' aria-hidden='true'></span> Adicionar"), new_artist_path, class: 'btn btn-primary pull-right' %>
  </div>
</div>

<div class="row">
  <div class="col-md-12">
    <table class="table table-striped table-hover">
      <thead>
        <tr>
          <th>Artista</th>
          <th>Telefone</th>
          <th>E-mail</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% @artists.each do |artist| %>
        <tr>
          <td><%= artist.name %></td>
          <td><%= artist.phone %></td>
          <td><%= mail_to(artist.email, artist.email) %></td>
          <td class="text-right">
            <%= link_to raw("<span class='glyphicon glyphicon-pencil' aria-hidden='true'></span> Editar"), edit_artist_path(artist), class: 'btn btn-warning btn-xs' %>
            <%= link_to raw("<span class='glyphicon glyphicon-trash' aria-hidden='true'></span> Remover"),  artist,  method: :delete, data: { confirm: "Ter certeza que deseja remover este artista?" }, class: "btn btn-danger btn-xs" %>
          </td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/home/index.html.erb
<h1>Bem vindo ao DAE ARS, <%= current_user.email %>!</h1>

app/views/institutions/_form.html.erb
<%= form_for @institution do |f| %>
  <div class="row">
    <div class="form-group col-md-4">
      <%= f.label :name, 'Nome' %>
      <%= f.text_field :name, class: 'form-control' %>
    </div>
  </div>
  <div class="row">
    <div class="form-group col-md-5">
      <%= f.label :address, 'Endereço' %>
      <%= f.text_field :address, class: 'form-control' %>
    </div>
  </div>
  <div class="row">
    <div class="form-group col-md-12">
      <%= f.submit 'Salvar', class: 'btn btn-primary btn-lg' %>
    </div>
  </div>
<% end %>

app/views/institutions/edit.html.erb
<div class="row">
  <div class="col-md-12">
    <%= render 'form' %>
  </div>
</div>

app/views/institutions/index.html.erb
<div class="row">
  <div class="col-md-12">
    <%= link_to raw("<span class='glyphicon glyphicon-plus' aria-hidden='true'></span> Adicionar"), new_institution_path, class: 'btn btn-primary pull-right' %>
  </div>
</div>

<div class="row">
  <div class="col-md-12">
    <table class="table table-striped table-hover">
      <thead>
        <tr>
          <th>Instituição</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% @institutions.each do |institution| %>
        <tr>
          <td><%= institution.name %></td>
          <td class="text-right">
            <%= link_to raw("<span class='glyphicon glyphicon-pencil' aria-hidden='true'></span> Editar"), edit_institution_path(institution), class: 'btn btn-warning btn-xs' %>
            <%= link_to raw("<span class='glyphicon glyphicon-trash' aria-hidden='true'></span> Remover"),  institution,  method: :delete, data: { confirm: "Ter certeza que deseja remover esta instituição?" }, class: "btn btn-danger btn-xs" %>
          </td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/institutions/new.html.erb
<div class="row">
  <div class="col-md-12">
    <%= render 'form' %>
  </div>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'DAE ARS', root_path, class: 'navbar-brand' %>
    </div>
    <div id="navbar" class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li class="<%= is_active? 'home' %>"><%= link_to 'Home', root_path %></li>
        <li class="<%= is_active? 'artists' %>"><%= link_to 'Artistas', artists_path %></li>
        <li class="<%= is_active? 'modalities' %>"><%= link_to 'Modalidades Artísticas', modalities_path %></li>
        <li class="<%= is_active? 'institutions' %>"><%= link_to 'Instituições', institutions_path %></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
        <li>
          <%= link_to current_user.email %>
        </li>
        <li>
          <%= link_to 'Sair', destroy_user_session_path, method: :delete %>
        </li>
        <% end %>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>DAE ARS</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/navbar' if user_signed_in? %>

<div class="container main-container">
  <% if notice %>
  <div class="row">
    <div class="col-md-12">
      <div class="alert alert-success alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <%= notice %>
      </div>
    </div>
  </div>
  <% end %>
  <% if alert %>
  <div class="row">
    <div class="col-md-12">
      <div class="alert alert-danger alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <%= alert %>
      </div>
    </div>
  </div>
  <% end %>
  <%= yield %>
</div>

</body>
</html>

app/views/modalities/_form.html.erb
<%= form_for @modality do |f| %>
  <div class="row">
    <div class="form-group col-md-4">
      <%= f.label :name, 'Nome' %>
      <%= f.text_field :name, class: 'form-control' %>
    </div>
  </div>
  <div class="row">
    <div class="form-group col-md-12">
      <%= f.submit 'Salvar', class: 'btn btn-primary btn-lg' %>
    </div>
  </div>
<% end %>

app/views/modalities/index.html.erb
<div class="row">
  <div class="col-md-12">
    <%= link_to raw("<span class='glyphicon glyphicon-plus' aria-hidden='true'></span> Adicionar"), new_modality_path, class: 'btn btn-primary pull-right' %>
  </div>
</div>

<div class="row">
  <div class="col-md-12">
    <table class="table table-striped table-hover">
      <thead>
        <tr>
          <th>Modalidade</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% @modalities.each do |modality| %>
        <tr>
          <td><%= modality.name %></td>
          <td class="text-right">
            <%= link_to raw("<span class='glyphicon glyphicon-pencil' aria-hidden='true'></span> Editar"), edit_modality_path(modality), class: 'btn btn-warning btn-xs' %>
            <%= link_to raw("<span class='glyphicon glyphicon-trash' aria-hidden='true'></span> Remover"),  modality,  method: :delete, data: { confirm: "Ter certeza que deseja remover esta modalidade?" }, class: "btn btn-danger btn-xs" %>
          </td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Entrar", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Cadastrar-se", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Esqueceu sua senha?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Não recebeu instruções de confirmação?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Não recebeu instruções de desbloqueio?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Entrar com #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>